backend:
  name: git-gateway
  branch: master
  commit_messages:
  create: Create {{collection}} "{{slug}}"
  update: Update {{collection}} "{{slug}}"
  delete: Delete {{collection}} "{{slug}}"
  uploadMedia: Upload "{{path}}"
  deleteMedia: Delete "{{path}}"
  openAuthoring: "{{message}}"
media_folder: public/images
public_folder: /images

collections:
  - name: site_settings
    label: Site Settings
    files:
      - label: "Contact Details"
        name: "contact"
        file: content/settings/contact.md
        editor:
          preview: false
        fields:
          - { label: Phone Number, name: telephone, widget: string }
          - { label: Email Address, name: email, widget: string }
      - label: Config
        name: config
        file: "content/settings/settings.md"
        editor:
          preview: false
        fields:
          - { label: Site Title for Browser Tab, name: title, widget: string }
          - { label: Site Description, name: description, widget: text }
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: content/pages/home.md
        fields:
          - label: Page Metadata
            name: pageMeta
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Cover Image
                name: media
                widget: object
                required: false
                fields:
                  - label: Alt
                    name: alt
                    widget: string
                    required: true
                  - label: Image
                    name: image
                    widget: image
                    required: true

          - label: Cards
            name: cards
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Items
                name: items
                widget: list
                min: 3
                max: 3
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: SubTitle
                    name: subTitle
                    widget: string
          - label: Features
            name: features
            widget: object
            fields:
              - label: Items
                name: items
                widget: list
                min: 2
                max: 4
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: SubTitle
                    name: subTitle
                    widget: string
                  - label: Mute Backgroundback
                    name: backgroundMuted
                    widget: boolean
                    required: false
          - label: Pricing
            name: pricing
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Items
                name: items
                widget: list
                min: 3
                max: 3
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: SubTitle
                    name: subTitle
                    widget: string

      - label: About
        name: about
        file: content/pages/about.md
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Cover Image
                name: media
                widget: object
                required: false
                fields:
                  - label: Alt
                    name: alt
                    widget: string
                    required: true
                  - label: Image
                    name: image
                    widget: image
                    required: true
                    tagname:

          - label: Content
            name: content
            widget: markdown
            buttons:
              - heading-three
              - link
            modes:
              - rich_text

      - label: Contact
        name: contact
        file: content/pages/contact.md
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Type
                name: type
                widget: hidden
                default: Hero
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Cover Image
                name: media
                widget: object
                required: false
                fields:
                  - label: Alt
                    name: alt
                    widget: string
                    required: true
                  - label: Image
                    name: image
                    widget: image
                    required: true
                    tagname:

      - label: Instructors
        name: instructors
        file: content/pages/instructors.md
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Cover Image
                name: media
                widget: object
                required: false
                fields:
                  - label: Alt
                    name: alt
                    widget: string
                    required: true
                  - label: Image
                    name: image
                    widget: image
                    required: true
                    tagname:

          - label: Team
            name: team
            widget: object
            fields:
              - label: Instructors
                name: instructors
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Qualifications
                    name: qualifications
                    widget: list
                    fields:
                      - label: Qualification
                        name: qualification
                        widget: string
                  - label: Media
                    name: media
                    widget: object
                    required: false
                    fields:
                      - label: Alt
                        name: alt
                        widget: string
                        required: true
                      - label: Image
                        name: image
                        widget: image
                        required: true
                        tagname: ""
                        media_library:
                          config:
                            default_transformations:
                              - - width: 300
                                  crop: scale

      - label: FAQs
        name: faqs
        file: content/pages/faqs.md
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: SubTitle
                name: subTitle
                widget: string
              - label: Cover Image
                name: media
                widget: object
                required: false
                fields:
                  - label: Alt
                    name: alt
                    widget: string
                    required: true
                  - label: Image
                    name: image
                    widget: image
                    required: true
                    tagname:
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - label: FAQ
                name: faq
                widget: markdown
                modes:
                  - rich_text
